spring:
  application:
    name: userservice
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.174.130:8848
        secure: false

#  zipkin:
#    base-url: http://192.168.174.130:9411
#    sender:
#      type: web

#server:
#  port: 8080

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:10000/eureka
#  instance:
#    prefer-ip-address: true
##    hostname: provider
#    instance-id: ${spring.cloud.client.ip-address}:${server.port}
#debug: true

#orderservice:
#  ribbon:
#    listOfServers: localhost:8080,localhost:8081
server:
  port: 8085
